import { Document } from './document.model';

export const MOCKDOCUMENTS: Document[] = [
  new Document(
    '1',
    'Ray-Ban Aviator Classic',
    'Iconic metal frame sunglasses with crystal green lenses. Perfect for outdoor activities.',
    'https://www.ray-ban.com/usa/sunglasses/RB3025%20UNISEX%20aviator%20classic-gold/805289439899',
    [],
    163.00,
    'Ray-Ban',
    'Metal',
    'Green',
    '100% UV Protection',
    'https://images.ray-ban.com/is/image/RayBan/805289439899__001.png?impolicy=RB_Product'
  ),
  new Document(
    '2',
    'Oakley Holbrook',
    'Sporty and durable sunglasses ideal for active lifestyles, featuring Plutonite lenses.',
    'https://www.oakley.com/en-us/product/W0OO9102',
    [],
    145.00,
    'Oakley',
    'O Matter™',
    'Gray',
    '100% UV Protection',
    'https://images.oakley.com/is/image/OakleyEYE/OO9102-36?$oakley-product$'
  ),
  new Document(
    '3',
    'Warby Parker Clark',
    'Classic rectangular frame in Cognac Tortoise. Lightweight and stylish for everyday use.',
    'https://www.warbyparker.com/eyeglasses/men/clark/cognac-tortoise',
    [],
    95.00,
    'Warby Parker',
    'Acetate',
    'Clear',
    'Yes',
    'https://cdn.warbyparker.com/product-images/v1/glasses/clark/clark-cognac-tortoise-front.jpg'
  ),
  new Document(
    '4',
    'Persol PO3019S',
    'Handmade in Italy, features iconic arrow hinges and crystal lenses.',
    'https://www.persol.com/usa/PO3019S--95-31/8053672064744.html',
    [],
    280.00,
    'Persol',
    'Acetate',
    'Green',
    '100% UV Protection',
    'https://assets.persol.com/is/image/persol/PO3019S__95-31__STD__shad__fr.png'
  ),
  new Document(
    '5',
    'Tom Ford FT5401',
    'Elegant square frame glasses with subtle logo detailing on the temples.',
    'https://www.farfetch.com/shopping/men/tom-ford-ft5401-item-15083391.aspx',
    [],
    380.00,
    'Tom Ford',
    'Acetate',
    'Clear',
    'Optional',
    'https://cdn-images.farfetch-contents.com/15/08/33/91/15083391_28226903_1000.jpg'
  ),
  new Document(
    '6',
    'Maui Jim Cliff House',
    'Aviator-style sunglasses with PolarizedPlus2® lens technology and lightweight titanium frame.',
    'https://www.mauijim.com/US/en_US/sunglasses/aviators/cliff-house-gold-neutral-grey/247-02.html',
    [],
    299.00,
    'Maui Jim',
    'Titanium',
    'Neutral Grey',
    'PolarizedPlus2® UV Protection',
    'https://cdn.mauijim.com/eyewear/247-02-angle.jpg'
  ),
  new Document(
    '7',
    'Oliver Peoples Gregory Peck',
    'Inspired by the iconic style of Gregory Peck in "To Kill a Mockingbird", handcrafted in Italy.',
    'https://www.oliverpeoples.com/usa/gregory-peck/OV5186.html',
    [],
    370.00,
    'Oliver Peoples',
    'Acetate',
    'Clear',
    'Yes',
    'https://oliverpeoples.com/on/demandware.static/-/Sites-oliverpeoples-catalog/default/dw2b3bc8a2/images/large/OV5186/OV5186_1485_2.jpg'
  ),
  new Document(
    '8',
    'Gucci GG0061S',
    'Fashion-forward cat-eye frame with signature Gucci design details.',
    'https://www.gucci.com/us/en/pr/eyewear/womens-eyewear/womens-sunglasses/gg0061s-cat-eye-sunglasses-p-819722J07401090',
    [],
    435.00,
    'Gucci',
    'Acetate',
    'Black',
    '100% UV Protection',
    'https://media.gucci.com/style/DarkGray_Center_0_0_980x980/1734985817/819722_J0740_1090_001_100_0000_Light-cat-eye-optical-frame.jpg'
  ),
  new Document(
    '9',
    'Zeiss Blue Light Glasses',
    'Advanced lenses to reduce blue light exposure and eye strain from screens.',
    'https://www.zeiss.com/vision-care/int/eye-care/blue-light-protection.html',
    [],
    120.00,
    'Zeiss',
    'Plastic',
    'Clear (Blue Block)',
    'Blue Light Filtering',
    'https://www.zeiss.com/content/dam/vision-care/us/products/blue-light/zeiss-blue-protect-lenses.jpg'
  ),
  new Document(
    '10',
    'Moscot Lemtosh',
    'Timeless Moscot design worn by creatives and intellectuals for decades.',
    'https://moscot.com/products/lemtosh',
    [],
    300.00,
    'Moscot',
    'Acetate',
    'Clear',
    'Optional',
    'https://cdn.shopify.com/s/files/1/0013/8336/products/LEMTOSH_BLONDE_ANGLE_1024x1024.jpg'
  )
];
